apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        ports:
        - containerPort: 80
        name: nginx
        volumeMounts:
        - name: webservercontent
          mountPath: /usr/share/nginx/html
      volumes:
      - name: webservercontent
        persistentVolumeClaim:
          claimName: nfs