apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-world-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules: #path based routing
  - host: ingress.nathan.local
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx-service-main
          servicePort: 80
      - path: /blue
        backend:
          serviceName: nginx-service-blue
          servicePort: 80   
      - path: /green
        backend:
          serviceName: nginx-service-green
          servicePort: 80
---