apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless
  namespace: rabbitmq
spec:
  clusterIP: None
  ports:
  - port: 4369
    targetPort: 4369
    name: epmd
  - port: 5672
    targetPort: 5672
    name: amqp
  selector:
    app.kubernetes.io/name: production-rabbitmqcluster
  type: ClusterIP